import localFonts from 'next/font/local'
import AOSClient from './components/AOSClient'
import './globals.css'
export const metadata = {
  title: "Fastr",
  description: "Generated by Fastr",
};
const MIT = localFonts({
  src: [
    {
      path: '../../public/fonts/mit-block-font.otf',
      weight: '800',
      style: 'normal'
    }
  ],
  variable: '--font-MIT',
  display: 'swap',
})

export default function Home({ Component, pageProps }) {
  const title = 'FASTR'
  return (
    <>
      <AOSClient />
      <div className="main-title flex hover:cursor-none space-x-4">
        {title.split("").map((char, index) => (
          <span 
            key={index} 
            data-aos="zoom-in" 
            data-aos-duration="1000"
            data-aos-delay={index * 500} 
            className={` ${MIT.className} main-tile text-neutral-100  bg-none font-extrabold text-[10rem] transform transition-transform duration-400 hover:text-shadow-lg horder hover:text-shadow-blue-600`}>
            {char === " " ? "\u00A0" : char}
          </span>
        ))

        }
      </div>
    </>
  );
}
